fix

diff --git a/.github/workflows/AutoRelease.yaml b/.github/workflows/AutoRelease.yaml
--- a/.github/workflows/AutoRelease.yaml
+++ b/.github/workflows/AutoRelease.yaml
@@ -332,8 +332,10 @@ jobs:
 
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa student@${{ vars.SERVER_URL }} "
             echo 'Installing package...'
-            apt install -y ~/AdrienMaximePaul/simeis-server_${VERSION}.deb || {
-              DEBIAN_FRONTEND=noninteractive apt install -y ~/AdrienMaximePaul/simeis-server_${VERSION}.deb
+            sudo dpkg -i ~/AdrienMaximePaul/simeis-server_${VERSION}.deb || {
+              echo 'dpkg failed, trying apt-get install with fix-broken'
+              sudo apt-get install -f -y
+              sudo dpkg -i ~/AdrienMaximePaul/simeis-server_${VERSION}.deb
             }
           "
 
